version: 0.2

#env:
  #variables:
     # key: "value"
     # key: "value"
  #parameter-store:
     # key: "value"
     # key: "value"

phases:
  install:
    commands:
      - echo "ja_JP.UTF-8 UTF-8" > /etc/locale.gen
      - apt-get update -y
      - apt-get install -y python2.7-dev python-setuptools locales
      - easy_install pip
      - pip install awscli
      # - command
  #pre_build:
    #commands:
      # - command
      # - command
  build:
    commands:
      - env |sort
      - git --version
      - |
          if [ -d .git ]; then
            BRANCH=`git rev-parse --abbrev-ref HEAD`
            if [ ${BRANCH} = 'test' ]; then
              echo "test branch"
            elif [ ${BRANCH} = 'develop' ]; then
              echo "develop branch"
            elif [ ${BRANCH} = 'staging' ]; then
              echo "staging branch"
            elif [ ${BRANCH} = 'master' ]; then
              echo "master branch"
            else
              echo 'did not match any deployment branches'
            fi
          else
            echo 'No .git directory found.'
            case "${CODEBUILD_INITIATOR}" in
            *test*) echo "CODEBUILD_INITIATOR: test";;
            *dev*) echo "CODEBUILD_INITIATOR: develop";;
            *stg*) echo "CODEBUILD_INITIATOR: staging";;
            *master*) echo "CODEBUILD_INITIATOR: master";;
            *     ) echo 'did not match any deployment branches';;
            esac
          fi
          echo "done"
    #commands:
      # - command
#artifacts:
  #files:
    # - location
    # - location
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - paths
