version: 0.2

#env:
  #variables:
     # key: "value"
     # key: "value"
  #parameter-store:
     # key: "value"
     # key: "value"

phases:
  install:
    commands:
      - apt-get update -y
      - apt-get install -y python2.7-dev python-setuptools
      - easy_install pip
      - pip install awscli
      # - command
  #pre_build:
    #commands:
      # - command
      # - command
  build:
    commands:
      - env |sort
      - git --version
      - |
          if [ -d .git ]; then
            BRANCH=`git rev-parse --abbrev-ref HEAD`
            if [ ${BRANCH} = 'test' ]; then
              aws s3 cp dist/ s3://test-shl-wrtc-service/ --recursive
            elif [ ${BRANCH} = 'develop' ]; then
              aws s3 cp dist/ s3://shl-wrtc-service/ --recursive
            elif [ ${BRANCH} = 'staging' ]; then
              aws s3 cp dist/ s3://stg-shl-wrtc-service/ --recursive
            elif [ ${BRANCH} = 'master' ]; then
              aws s3 cp dist/ s3://prd-shl-wrtc-service/ --recursive
            else
              echo 'did not match any deployment branches'
            fi
          else
            echo 'No .git directory found.'
            case "${CODEBUILD_INITIATOR}" in
            *test*) aws s3 cp dist/ s3://test-shl-wrtc-service/ --recursive;;
            *develop*) aws s3 cp dist/ s3://shl-wrtc-service/ --recursive;;
            *staging*) aws s3 cp dist/ s3://stg-shl-wrtc-service/ --recursive;;
            *master*) aws s3 cp dist/ s3://prd-shl-wrtc-service/ --recursive;;
            *     ) echo 'did not match any deployment branches';;
            esac
          fi
    #commands:
      # - command
#artifacts:
  #files:
    # - location
    # - location
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - paths
